pywaw/meetups/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from django.views import generic

from . import views

app_name = 'meetups'

urlpatterns = [
    url(r'^spotkania/$', views.MeetupsListView.as_view(), name='meetup_list'),
    url(r'^(?P<number>\d+)/$', views.MeetupDetailView.as_view(), name='meetup_detail'),
    url(r'^(?P<number>\d+)/promo/$', views.MeetupPromoView.as_view(), name='meetup_promo'),
    url(r'^sponsorzy/$', views.SponsorListView.as_view(), name='sponsor_list'),
    url(r'^prelegenci/$', views.SpeakerListView.as_view(), name='speaker_list'),
    url(r'^zgloszenie/$', views.TalkProposalCreateView.as_view(), name='talk_proposal'),
    url(r'^zgloszenie/potwierdzenie/$', views.TalkProposalConfirmationView.as_view(),
        name='talk_proposal_confirmation'),
    url(r'^atom/$', views.MeetupsAtomFeed(), name='atom_feed'),
    url(r'^rss/$', views.MeetupsRssFeed(), name='rss_feed'),

    # Legacy URL's from old website
    url(r'^historia/$', generic.RedirectView.as_view(url=reverse_lazy('meetups:meetup_list'), permanent=True)),
    url(r'^(?P<day>\d{2})-(?P<month>\d{2})-(?P<year>\d{4})/$', views.MeetupDateRedirectView.as_view(permanent=True),
        name='date_redirect'),
    url(r'^home/sponsor/$', generic.RedirectView.as_view(url=reverse_lazy('meetups:sponsor_list'), permanent=True)),
    url(r'^home/poradnik-prelegenta$',
        generic.RedirectView.as_view(url=reverse_lazy('meetups:speaker_list'), permanent=True)),
]

pywaw/misc/urls.py
from django.conf.urls import patterns, url
from . import views
from .sitemaps import sitemaps

urlpatterns = patterns('',
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^faq/$', views.FaqView.as_view(), name='faq'),
    url(r'^kodeks-postepowania/$', views.CocView.as_view(), name='coc'),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
)

pywaw/pywaw/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

admin.autodiscover()


urlpatterns = [
    path('', include('misc.urls', namespace='misc')),
    path(r'', include('meetups.urls', namespace='meetups')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pywaw/misc/models.py
import os
from django.conf import settings
from django.db import models
from django.utils.text import slugify


def slugify_upload_to(path, fields):

    def upload_to(instance, filename):
        extension = filename.split('.')[-1]
        slug = slugify(' '.join([str(getattr(instance, field)) for field in fields]))
        new_filename = '{0}.{1}'.format(slug, extension)
        return os.path.join(path, new_filename)

    return upload_to


class Partner(models.Model):
    name = models.CharField(max_length=200)
    url = models.URLField()
    logo = models.ImageField(upload_to=slugify_upload_to(settings.PARTNER_LOGOS_DIR, ['name']))
    is_public = models.BooleanField()

    def __str__(self):
        return self.name

pywaw/misc/views.py
from django.views import generic
from meetups import models as meetups_models
from . import models


class HomeView(generic.TemplateView):
    template_name = 'misc/home.html'

    def get_context_data(self):
        context = super().get_context_data()
        try:
            context['upcoming_meetup'] = meetups_models.Meetup.objects.get_upcoming()
        except meetups_models.Meetup.DoesNotExist:
            context['upcoming_meetup'] = None
        context['partners'] = models.Partner.objects.filter(is_public=True)
        return context


class FaqView(generic.TemplateView):
    template_name = 'misc/faq.html'


class CocView(generic.TemplateView):
    template_name = 'misc/coc.html'

pywaw/templates/misc/coc.html
{% extends "base_content.html" %}

{% load staticfiles %}

{% block title %}Kodeks Postępowania{% endblock %}

{% block og_title %}Kodeks Postępowania{% endblock %}

{% block subcontent %}
<div class="margin-bottom-large faq">
    <h1>Kodeks Postępowania</h1>
    <h2>Cel</h2>
    <p>Podstawowym celem istnienia <i>Kodeksu Postępowania</i> jest otwartość na jak największą liczbę osób o jak najbardziej urozmaiconych i różnorodnych korzeniach. Z tego powodu zobowiązujemy się do zapewnienia życzliwej, bezpiecznej i przyjaznej atmosfery wszystkim, bez względu na płeć, orientację seksualną, sprawność, pochodzenie etniczne, status społeczno-ekonomiczny i religię (lub jej brak).</p>
    <p>Ten Kodeks postępowania nakreśla zarówno nasze oczekiwania wobec wszystkich, którzy uczestniczą w naszej społeczności, jak i konsekwencje niedopuszczalnych zachowań.</p>
    <p>Zapraszamy wszystkich uczestników i uczestniczki naszych wydarzeń do pomocy w kreowaniu doświadczeń, które będą bezpieczne i pozytywne dla każdego.</p>
    <h2>Poczucie wspólnoty i otwartości</h2>
    <p>Dodatkowym celem <i>Kodeksu Postępowania</i> jest zwiększenie poczucia wspólnoty i otwartości poprzez zachęcanie uczestników i uczestniczek do rozpoznawania i wzmacniania związków między naszymi zachowaniami a ich wpływem na społeczność.</p>
    <p>Społeczności odzwierciedlają społeczeństwa, w ramach których istnieją, dlatego też pozytywne oddziaływanie jest kluczowe dla przeciwdziałania wielu formom nierówności i nadużyć władzy istniejących w społeczeństwie.</p>
    <p>Jeśli widzisz kogoś wkładającego szczególny wysiłek, by uczynić naszą społeczność przyjazną, życzliwą i zachęcającą wszystkich uczestników do wnoszenia w nią jak największego wkładu – chcielibyśmy o tym wiedzieć.</p>
    <h2>Zachowania oczekiwane</h2>
    <ul>
        <li>Uczestnicz w sposób autentyczny i aktywny. Robiąc to, przyczyniasz się do zdrowia i żywotności tej społeczności.</li>
        <li>Zachowuj rozwagę i szacunek w swoich słowach i czynach.</li>
        <li>Spróbuj współpracy przed konfliktem.</li>
        <li>Powstrzymuj się przed poniżającymi, dyskryminującymi lub niepokojącymi zachowaniami i słowami.</li>
        <li>Zwracaj uwagę na swoje otoczenie i innych uczestników. Ostrzeż społeczność, jeśli zauważysz niebezpieczną sytuację, kogoś potrzebującego pomocy lub naruszenie <i>Kodeksu Postępowania</i>, nawet jeśli wydają się nieistotne.
        </li>
    </ul>
    <h2>Zachowania niedopuszczalne</h2>
    <p>Zachowania niedopuszczalne to między innymi: zastraszające, nękające, obraźliwe, dyskryminujące, uwłaczające i poniżające słowa lub czyny dowolnego uczestnika naszej społeczności w Internecie, na wszelkich powiązanych wydarzeniach oraz w komunikacji prywatnej dotyczącej spraw społeczności. Miejsca spotkań społeczności mogą być współdzielone z członkami społeczeństwa; szanuj wszystkich obecnych w danym miejscu.</p>
    <p>Nękanie to między innymi: szkodliwe lub krzywdzące słowne lub pisemne komentarze dotyczące płci, orientacji seksualnej, pochodzenia, religii, niepełnosprawności; niewłaściwe użycie nagości lub ilustracji o podtekście seksualnym w przestrzeni publicznej (w tym w prezentacjach); celowe zastraszanie, prześladowanie (tzw. stalking) lub śledzenie; niepokojące fotografowanie lub nagrywanie; trwałe zaburzanie wystąpień i innych wydarzeń; niewłaściwy kontakt fizyczny i niemile widziane zainteresowanie seksualne.</p>
    <h2>Konsekwencje niedopuszczalnych zachowań</h2>
    <p>Niedopuszczalne zachowanie ze strony dowolnego uczestnika społeczności – w tym sponsorów i osób decyzyjnych – nie będzie tolerowane. Osoby poproszone o zaprzestanie niedopuszczalnego zachowania powinny się natychmiast do danej prośby zastosować.</p>
    <p>Jeśli uczestnik społeczności zachowuje się niedopuszczalnie, organizatorzy mogą podjąć dowolne działania, które uznają za właściwe, włącznie z tymczasowym lub stałym wykluczeniem ze społeczności bez ostrzeżenia (i bez zwrotu pieniędzy w przypadku wydarzeń płatnych).</p>
    <h2>Doświadczasz niedopuszczalne zachowanie</h2>
    <p>Jeśli doświadczasz lub widzisz niedopuszczalne zachowanie – lub masz inne uwagi – jak najszybciej powiadom o tym organizatora. Zgłość nam zachowanie osobiście lub przy wykorzystaniu dowolnego kanału online (np. poprzez email <a href="mailto:info@pywaw.org">info@pywaw.org</a>). Organizatorzy są także dostępni, by wspomóc uczestników w kontaktach z lokalnymi organami egzekwowania prawa i by wspierać poczucie bezpieczeństwa osób doświadczających niedopuszczalnych zachowań. Jeśli osoba poszkodowana wyrazi zapotrzebowanie, organizatorzy zapewnią też odpowiednią eskortę.</p>
    <h2>Skargi</h2>
    <p>Jeśli uważasz, że informacja o naruszeniu przez ciebie tego <i>Kodeksu Postępowania</i> jest fałszywa lub niesprawiedliwa, zawiadom organizatorów wraz ze zwięzłym opisem swojej skargi. Twoja skarga zostanie rozpatrzona zgodnie z istniejącymi zasadami.</p>
    <h2>Zakres</h2>
    <p>Oczekujemy, że wszyscy uczestnicy społeczności (organizatorzy, zarówno opłacani, jak i wolontariusze; sponsorzy; pozostali goście) będą przestrzegać <i>Kodeksu Postępowania</i> we wszelkich miejscach spotkań społeczności (online i w świecie rzeczywistym), jak i w komunikacji prywatnej dotyczącej spraw społeczności.</p>
    <br>
    <p>Ten <i>Kodeks Postępowania</i> powstał na podstawie <a href="https://berlincodeofconduct.org/pl/" target="_blank">Berlińskiego Kodeksu Postępowania</a></p>
</div>
{% endblock %}

pywaw/templates/misc/faq.html
{% extends "base_content.html" %}

{% block title %}FAQ{% endblock %}

{% block og_title %}FAQ{% endblock %}

{% block subcontent %}
    <div class="margin-bottom-large faq">
        <h1>FAQ</h1>
        <ol class="page-menu margin-bottom-large">
            <li><a href="#for-attendees">Dla uczestników</a></li>
            <li><a href="#for-speakers">Dla prelegentów</a></li>
            <li><a href="#for-sponsors">Dla sponsorów</a></li>
        </ol>
        <div id="for-speakers">
            <h2>Dla prelegentów</h2>
            <h3>Jak się zgłosić?</h3>
                <p>Prosimy przesyłać propozycję prezentacji za pomocą <a href="{% url "meetups:talk_proposal" %}">formularza zgłoszeniowego</a>.</p>
            <h3>Ile czasu będzie przeznaczone na moją prezentację?</h3>
                <p>Standardowo jedna prezentacja trwa około 18 minut. Staramy się pilnować wyznaczonego czasu i po jego przekroczeniu będziemy prosić prelegenta o jak najszybsze zakończenie wystąpienia. Na jednym spotkaniu odbywają się maksimum 4 prezentacje.</p>
            <h3>Co powinienem zrobić w dniu prezentacji?</h3>
                <p>Prosimy prelegentów o przybycie minimum 15 minut przed rozpoczęciem spotkania, abyśmy mogli rozwiązać potencjalne problemy np. z podłączeniem laptopa do rzutnika czy internetu.</p>
            <h3>Co powinienem zrobić po prezentacji?</h3>
                <p>Prosimy o przesłanie nam materiałów prezentowanych podczas prelekcji (np. slajdy, kod) abyśmy mogli umieścić je na podstronie spotkania.</p>
            <h3>Czy dozwolone są prezentacje reklamujące komercyjne produkty lub ogłoszenia rekrutacyjne?</h3>
                <p>Takie prezentacje nie są wpisywane do agendy, ale po głównych prezentacjach mamy czas przeznaczony na tego typu krótkie ogłoszenia. Prosimy poinformować nas przed spotkaniem o chęci wystąpienia.</p>
        </div>
        <div id="for-attendees" class="margin-top-big">
            <h2>Dla uczestników</h2>
            <h3>W jakim języku odbywają się spotkania?</h3>
                <p>Większość prezentacji prowadzona jest w języku polskim, w tym języku prowadzimy też spotkanie. Zdarzają się jednak prezentacje w języku angielskim - zostają one odpowiednio oznaczone w agendzie.</p>
            <h3>Jak wyglądają spotkania PyWaw?</h3>
                <p>W ramach spotkań odbywają się 2-3 prezentacje związane z Pythonem i ogólnie IT. Następnie większość uczestników zostaje na networking przy piwie. Zachęcamy do zapoznania się z <a href="https://www.youtube.com/watch?v=Rrbpnrs8neM">video o naszych spotkaniach</a>.</p>
        </div>
        <div id="for-sponsors" class="margin-top-big">
            <h2>Dla sponsorów</h2>
            <h3>Jak zostać sponsorem?</h3>
                <p>Prosimy o kontakt mailowy na info@pywaw.org gdzie omówimy szczegóły.</p>
            <h3>Na co mogę liczyć jako sponsor?</h3>
                <p>Sponsor naszych spotkań może liczyć na:</p>
                <ul>
                    <li>umieszczenie loga sponsora na głównej stronie PyWaw obok zapowiadanego spotkania,</li>
                    <li>umieszczenie loga sponsora na podstronie spotkania,</li>
                    <li>umieszczenie loga i opisu sponsora na podstronie “Sponsorzy”,</li>
                    <li>wymienienie jako sponsor spotkania podczas zapowiedzi spotkania przez organizatorów,</li>
                    <li>pojawienia się specjalnej notki o sponsorze spotkania w mediach społecznościowych (Facebook/Twitter),</li>
                    <li>umieszczenie swojego baneru w sali spotkania.</li>
                </ul>
            <h3>Na co przeznaczane są pieniądze?</h3>
                <p>W zależności od potrzeb przeznaczamy uzyskane pieniądze na następujące cele:</p>
                <ul>
                    <li>zakup napojów i jedzenia dla uczestników spotkania,</li>
                    <li>pokrycie kosztów związanych z przejazdem i pobytem w Warszawie zaproszonego prelegenta,</li>
                    <li>wynajęcie miejsca spotkań,</li>
                    <li>organizację innych wydarzeń niż comiesięczne spotkania, takich jak hackatony czy sprinty,</li>
                    <li>utrzymywanie infrastruktury PyWaw (domena, hosting),</li>
                    <li>ufundowanie drobnych podarunków (np. książki) rozlosowanych podczas spotkania.</li>
                </ul>
            <h3>Jak wygląda rozliczenie sponsoringu?</h3>
                <p>PyWaw wystawia faktury VAT.</p>
        </div>
    </div>
{% endblock %}

pywaw/templates/misc/home.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}Home{% endblock %}

{% block og_title %}Home{% endblock %}

{% block js %}
{% if upcoming_meetup.venue %}
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhNca45HD9Q_OMp-g2qNlSLwmOqaKCwXs&amp;sensor=false"></script>
<script type="text/javascript">
    function initialize() {
        var venue = new google.maps.LatLng({{ upcoming_meetup.venue.latitude }}, {{ upcoming_meetup.venue.longitude }});
        var mapOptions = {
            center: venue,
            zoom: 15,
            mapTypeId: google.maps.MapTypeId.ROADMAP,
            scrollwheel: false,
            zoomControl: false,
            mapTypeControl: false,
            scaleControl: false,
            streetViewControl: false,
            rotateControl: false,
            fullscreenControl: false
        };
        var map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
        var marker = new google.maps.Marker({
            position: venue
        });
        marker.setMap(map);
    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>
{% endif %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="alert alert-info discord-invite">
        <p><strong>Dołącz do naszego serwera Discord!</strong> Zapraszamy do dyskusji na tematy dotyczące Pythona, PyWaw i nie tylko.</p>
        <a href="https://discord.gg/WJdEpsX" target="_blank" class="button discord-join-button"><img src="{% static 'img/discord.png' %}">&nbsp;Dołącz</a>
    </div>
</div>
<div class="container">
    {% if upcoming_meetup %}
    <div class="row">
        <div class="span2 img-tip">
            <div class="line-orange"></div>
        </div>
        <div class="span10">
            <h1><a href="{{ upcoming_meetup.get_absolute_url }}">Następne spotkanie {{ upcoming_meetup }}</a></h1>
        </div>
    </div>
    <div class="row">
        <div class="span5 offset2">
            <h4 class="date"><span class="day">{{ upcoming_meetup.date|date:"l" }}, </span>{{ upcoming_meetup.date|date:"d.m.Y" }} <span class="pull-right"><i class="icon-clock"></i> {{ upcoming_meetup.date|date:"H:i" }}</span></h4>
            {% if upcoming_meetup.online_event %}
            <h5 class="online-event">
                <span>
                    <span class="icon-globe"> </span>
                    Spotkanie Online
                </span>
                <a href="{{upcoming_meetup.online_event}}" target="_blank" class="button button--join button--success">DOŁĄCZ</a>
            </h5>
            <div class="text-center">
                <a href="{{ upcoming_meetup.get_absolute_url }}" class="button button-block margin-top-normal more">WIĘCEJ INFORMACJI</a>
            </div>
            {% elif upcoming_meetup.venue %}
            <h5 class="location"><img src="{% static 'img/location.png' %}" alt="Lokalizacja" class="icon-location-home"> {{ upcoming_meetup.venue.name }}, {{ upcoming_meetup.venue.address }}</h5>
            <div class="text-center">
                <div class="clearfix">
                    <a href="https://maps.google.com/maps?q={{ upcoming_meetup.venue.latitude }},{{ upcoming_meetup.venue.longitude }}" target="_blank">
                        <div class="margin-top-normal" itemprop="geo" itemscope itemtype="http://schema.org/GeoCoordinates">
                            <div id="map-canvas"></div>
                            <meta itemprop="latitude" content="{{ upcoming_meetup.venue.latitude }}">
                            <meta itemprop="longitude" content="{{ upcoming_meetup.venue.longitude }}">
                        </div>
                    </a>
                </div>
                <a href="{{ upcoming_meetup.get_absolute_url }}" class="button button-block margin-top-normal more">WIĘCEJ INFORMACJI</a>
            </div>
            {% endif %}
        </div>
        <div class="span5 box-users">
            {% for talk in upcoming_meetup.talks.all %}
            <div class="row">
                <div class="span1">
                	{% if talk.speakers.count == 1 %}
                	<img src="{% if talk.speakers.get.photo %}{{ talk.speakers.get.photo.url }}{% else %}{% static 'img/avatar.png' %}{% endif %}" alt="Zdjęcie {{ speaker }}" class="img-user">
                	{% else %}
                	<div class="carousel slide" id="myCarousel">
                		<div class="carousel-inner">
	                    {% for speaker in talk.speakers.all %}
	                    <img src="{% if speaker.photo %}{{ speaker.photo.url }}{% else %}{% static 'img/avatar.png' %}{% endif %}" alt="Zdjęcie {{ speaker }}" class="img-user item">
	                    {% endfor %}
	                    </div>
	                </div>
                    {% endif %}
                </div>
                <div class="span4 link-grey">
                    <h5>
                    {% for speaker in talk.speakers.all %}
                        <a class="link-grey" href="{{ upcoming_meetup.get_absolute_url }}#speaker-{{ speaker|slugify }}">{{ speaker }}</a>{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                    </h5>
                    <p class="text-smaller"><a href="{{ upcoming_meetup.get_absolute_url }}#talk-{{ talk|slugify }}">{{ talk.title }}</a></p>
                </div>
            </div>
            {% endfor %}
            {% if not upcoming_meetup.is_ready %}
            <div class="more-info">
            	<h3>agenda w przygotowaniu</h3>
            </div>
            {% endif %}
        </div>
    </div>

    {% if upcoming_meetup.sponsors.exists %}
    <div class="row">
        <div class="span10 offset2 margin-top-normal">
            <h3 class="span2 text-sponsors text-left">SPONSORZY:</h3>
            <div class="row-fluid">
                <div class="sponsors">
                    <table class="row-fluid home-sponsors-table">
                        <tr>
                            {% for sponsor in upcoming_meetup.sponsors.all %}
                            <td>
                                <a href="{{ sponsor.website }}" target="_blank" class="no-hover">
                                    <img src="{{ sponsor.logo.url }}" alt="{{ sponsor.name }}">
                                </a>
                            </td>
                            {% if forloop.counter|divisibleby:4 %}</tr><tr>{% endif %}
                            {% endfor %}
                        </tr>
                    </table>
                    <div class="home-sponsors-mobile">
                        {% for sponsor in upcoming_meetup.sponsors.all %}
                        <div>
                            <a href="{{ sponsor.website }}" target="_blank" class="no-hover">
                                <img src="{{ sponsor.logo.url }}" alt="{{ sponsor.name }}">
                            </a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% else %}
    <div class="more-info">
        <h3>spotkanie w przygotowaniu</h3>
    </div>
    {% endif %}
</div>
<div class="container">
    <div class="row talk-proposal-landing">
        <p class="span6 offset2 talk-proposal-description">Chcesz wystąpić na kolejnym PyWaw? Zgłoś się już teraz!</p>
        <p class="span4"><a href="{% url "meetups:talk_proposal" %}" class="button button-block talk-proposal-button"><span class="plus-icon">+</span>Zgłoś prelekcję</a></p>
    </div>
</div>
<div class="box-home">
    <div class="container">
        <div class="row">
            <div class="span2 img-tip">
                <img src="{% static 'img/question.jpg' %}" alt="Informacje">
            </div>
            <div class="span10">
                <h2>Warszawska grupa użytkowników Pythona</h2>
                <div class="row">
                  <div class="video-landing">
                    <iframe width="800" height="410" src="http://www.youtube.com/embed/Rrbpnrs8neM" frameborder="0" allowfullscreen></iframe>
                  </div>
                </div>
                <div class="row">
                    <div class="span5">
                        <p><strong>PL</strong> PyWaw to cykliczne spotkania pasjonatów języka programowania Python z Warszawy i okolic. Projekt ten skierowany jest zarówno do studentów stołecznych uczelni, profesjonalnych deweloperów oraz wszystkich tych, którzy swoją przygodę z Pythonem dopiero zaczynają. Celem naszych spotkań jest wymiana doświadczenia pomiędzy programistami, integracja pythonowego środowiska Warszawy oraz propagowanie Pythona jako uniwersalnego języka programowania. Spotkania PyWaw odbywają się w każdy drugi lub trzeci poniedziałek miesiąca.</p>
                    </div>
                    <div class="span5">
                        <p><strong>EN</strong> PyWaw is a community that gathers Python hobbyists from Warsaw and its surroundings. This project is aimed at not only Computer Sciences students or professional developers, but also all of you who have just started the Python experience. Our goals are various – exchange our experiences and ideas, integration of Python people in Warsaw and spreading the fame of Python as a universal programming language. Our meetings are held every second (or third) Monday of a month. Feel free to join us anytime!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% if partners %}
<div class="container">
    <div class="row">
        <div class="span10 offset2 margin-top-big margin-bottom-big">
            <h2>Partnerzy</h2>
            <div class="row-fluid">
                <div class="pull-left">
                    {% for partner in partners %}
                    <a href="{{ partner.url }}" title="{{ partner.name }}" class="no-hover" target="_blank">
                        <img class="partner-logo" src="{{ partner.logo.url }}" alt="{{ partner.name }}">
                    </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
<script>
$('.carousel img:first-child').addClass('active');
$('.carousel').carousel();
</script>
{% endblock %}