pywaw/meetups/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from django.views import generic

from . import views

app_name = 'meetups'

urlpatterns = [
    url(r'^spotkania/$', views.MeetupsListView.as_view(), name='meetup_list'),
    url(r'^(?P<number>\d+)/$', views.MeetupDetailView.as_view(), name='meetup_detail'),
    url(r'^(?P<number>\d+)/promo/$', views.MeetupPromoView.as_view(), name='meetup_promo'),
    url(r'^sponsorzy/$', views.SponsorListView.as_view(), name='sponsor_list'),
    url(r'^prelegenci/$', views.SpeakerListView.as_view(), name='speaker_list'),
    url(r'^zgloszenie/$', views.TalkProposalCreateView.as_view(), name='talk_proposal'),
    url(r'^zgloszenie/potwierdzenie/$', views.TalkProposalConfirmationView.as_view(),
        name='talk_proposal_confirmation'),
    url(r'^atom/$', views.MeetupsAtomFeed(), name='atom_feed'),
    url(r'^rss/$', views.MeetupsRssFeed(), name='rss_feed'),

    # Legacy URL's from old website
    url(r'^historia/$', generic.RedirectView.as_view(url=reverse_lazy('meetups:meetup_list'), permanent=True)),
    url(r'^(?P<day>\d{2})-(?P<month>\d{2})-(?P<year>\d{4})/$', views.MeetupDateRedirectView.as_view(permanent=True),
        name='date_redirect'),
    url(r'^home/sponsor/$', generic.RedirectView.as_view(url=reverse_lazy('meetups:sponsor_list'), permanent=True)),
    url(r'^home/poradnik-prelegenta$',
        generic.RedirectView.as_view(url=reverse_lazy('meetups:speaker_list'), permanent=True)),
]

pywaw/misc/urls.py
from django.conf.urls import patterns, url
from . import views
from .sitemaps import sitemaps

urlpatterns = patterns('',
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^faq/$', views.FaqView.as_view(), name='faq'),
    url(r'^kodeks-postepowania/$', views.CocView.as_view(), name='coc'),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
)

pywaw/pywaw/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

admin.autodiscover()


urlpatterns = [
    path('', include('misc.urls', namespace='misc')),
    path(r'', include('meetups.urls', namespace='meetups')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pywaw/templates/base.html
<!DOCTYPE html>{% load staticfiles %}
<html lang="pl">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>PyWaw | {% block title %}{% endblock %}</title>
    <meta name="keywords" content="PyWaw, Python, grupa użytkowników, programowanie, barcamp, spotkanie, prezentacje">
    <meta name="description" content="PyWaw to cykliczne spotkania pasjonatów języka programowania Python z Warszawy i okolic.">

    <meta property="og:type" content="website">
    <meta property="og:title" content="PyWaw | {% block og_title %}{% endblock %}"/>
    <meta property="og:description" content="PyWaw to cykliczne spotkania pasjonatów języka programowania Python z Warszawy i okolic.">
    <meta property="og:url" content="http://{{ site.domain }}{{ request.get_full_path }}">
    <meta property="og:image" content="http://{{ site.domain }}{% static 'img/logo-big.png' %}"/>
    <meta property="og:site_name" content="PyWaw"/>

    <link href="{% static 'img/fav.png' %}" rel="shortcut icon">
    <link href="http://fonts.googleapis.com/css?family=Merriweather+Sans:400,300,700&amp;subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet">
    <link rel="alternate" type="application/rss+xml" href="{% url 'meetups:rss_feed' %}" />
    <link rel="alternate" type="application/atom+xml" href="{% url 'meetups:atom_feed' %}" />
    {% block css %}
    {% endblock %}
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <!--[if lt IE 9]>
    <script src="{% static 'js/html5shiv.js' %}"></script>
    <script src="{% static 'js/respond.src.js' %}"></script>
    <![endif]-->
    {% block js %}
    {% endblock %}
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-17174483-2');
    ga('send', 'pageview');
    </script>
</head>
<body>
	<div id="wrapper">
		<header>
			<div class="container">
				<div class="row">
					<div id="logo" class="span2">
						<a href="{% url 'misc:home' %}"><img src="{% static 'img/logo.png' %}" alt="PyWaw" class="logo"></a>
					</div>
					<div id="top">
						<div class="span7">
							<ul class="menu-top">
                {% url 'meetups:meetup_list' as meetup_list_url %}
                {% url 'meetups:speaker_list' as speaker_list_url %}
                {% url 'meetups:sponsor_list' as sponsor_list_url %}
                {% url 'misc:home' as home_url %}
                {% url 'misc:faq' as faq_url %}
                <li><a href="{{ home_url }}"{% if request.path == home_url %} class="active"{% endif %}>Home</a></li>
								<li><a href="{{ meetup_list_url }}"{% if request.path == meetup_list_url %} class="active"{% endif %}>Spotkania</a></li>
                <li><a href="{{ speaker_list_url }}"{% if request.path == speaker_list_url %} class="active"{% endif %}>Prelegenci</a></li>
                <li><a href="{{ sponsor_list_url }}"{% if request.path == sponsor_list_url %} class="active"{% endif %}>Sponsorzy</a></li>
                <li><a href="{{ faq_url }}"{% if request.path == faq_url %} class="active"{% endif %}>FAQ</a></li>
							</ul>
						</div>
						<div class="span3">
							<div class="top-links">
								<a href="http://www.meetup.com/PyWaw-Python-Warsaw-User-Group/" class="meetup" target="_blank"></a>
								<a href="http://facebook.com/PyWaw" class="facebook" target="_blank"></a>
								<a href="http://twitter.com/PyWaw" class="twitter" target="_blank"></a>
								<a href="http://youtube.com/PyWaw" class="youtube" target="_blank"></a>
								<div class="dropdown pull-right">
								    <a href="#" data-toggle="dropdown" class="dropdown-toggle rss" role="button" id="drop1"></a>
								    <ul aria-labelledby="drop1" role="menu" class="dropdown-menu">
	                    <li role="presentation"><a href="{% url 'meetups:rss_feed' %}" tabindex="-1" role="menuitem" target="_blank">RSS</a></li>
	                    <li role="presentation"><a href="{% url 'meetups:atom_feed' %}" tabindex="-1" role="menuitem" target="_blank">Atom</a></li>
			              </ul>
			          </div>
								<a href="mailto:info@pywaw.org" class="mail"></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</header>
        {% block content %}
        {%  endblock %}
		<div id="push"></div>
	</div>
	<footer>
		<div class="container">
			<div class="row">
				<div class="span2 img-tip">
					<div class="line-orange"></div>
				</div>
				<div class="span10">
					<div class="row margin-bottom-large">
						<div class="span2">
							<h5>Mapa witryny</h5>
							<ul>
								<li><a href="{% url 'misc:home' %}">Home</a></li>
								<li><a href="{% url 'meetups:meetup_list' %}">Spotkania</a></li>
                <li><a href="{% url 'meetups:speaker_list' %}">Prelegenci</a></li>
                <li><a href="{% url 'meetups:sponsor_list' %}">Sponsorzy</a></li>
                <li><a href="{% url 'misc:faq' %}">FAQ</a></li>
                <li><a href="{% url 'misc:coc' %}">Kodeks Postępowania</a></li>
							</ul>
						</div>
						<div class="span2">
							<h5>Jesteśmy na</h5>
							<ul>
								<li><a href="http://www.meetup.com/PyWaw-Python-Warsaw-User-Group/" target="_blank">Meetup</a></li>
								<li><a href="http://facebook.com/PyWaw" target="_blank">Facebook</a></li>
								<li><a href="http://twitter.com/PyWaw" target="_blank">Twitter</a></li>
								<li><a href="http://youtube.com/PyWaw" target="_blank">YouTube</a></li>
								<li><a href="https://discord.gg/WJdEpsX" target="_blank">Discord</a></li>
							</ul>
						</div>
						<div class="span2">
							<h5>Python w Polsce</h5>
							<ul>
                                <li><a href="http://pykonik.org" target="_blank">Pykonik</a></li>
                                <li><a href="http://pystok.org" target="_blank">PyStok</a></li>
                                <li><a href="http://www.meetup.com/Python-%C5%81od%C5%BA/" target="_blank">Python Łódź</a></li>
                                <li><a href="https://www.pylight.org/" target="_blank">PyLight</a></li>
							</ul>
						</div>
						<div class="span2">
							<h5>&nbsp;</h5>
							<ul>
                                <li><a href="http://pl.pycon.org/" target="_blank">PyCon PL</a></li>
								<li><a href="https://www.facebook.com/WroclawPythonUserGroup" target="_blank">wroc.py</a></li>
								<li><a href="https://www.meetup.com/PyRa-Poznan-Python-Programmers" target="_blank">PyRa</a></li>
								<li><a href="https://www.meetup.com/PyGda-pl/" target="_blank">PyGda</a></li>
							</ul>
					  </div>
					</div>
					<div class="row">
						<div class="span10">
							<div class="pull-left statistics">
								<h5 class="pull-left">Statystyki</h5>
								<p class="pull-left">
									Spotkania: <span>{{ meetups_stats.meetups_count }}</span>
									&bull; Prelegenci: <span>{{ meetups_stats.speakers_count }}</span>
									&bull; Prezentacje: <span>{{ meetups_stats.talks_count }}</span>
								</p>
							</div>
							<div class="pull-left stack margin-left-big">
								<h5 class="pull-left">Stack</h5>
								<p class="pull-left">Python {{ system.python }} &bull; Django {{ system.django }} &bull; <a href="https://github.com/PyWaw/pywaw.org/tree/{{ system.website }}" target="_blank">@{{ system.website|slice:":5" }}</a></p>
							</div>
						</div>
          </div>
          <div class="row margin-bottom-small">
            <div class="span10 margin-top-small">
              <div class="powered">Powered by <a href="http://sunscrapers.com" target="_blank"><img src="{% static 'img/sunscrapers.png' %}" alt="Powered by SUNSCRAPERS"></a></div>
            </div>
          </div>
				</div>
			</div>
		</div>
	</footer>
</body>
</html>

pywaw/templates/base_content.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="span2 img-tip">
            <div class="line-orange"></div>
        </div>
        <div class="span10">
            {% block subcontent %}
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}